# Generated by Django 4.2.6 on 2023-12-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_profile_email_alter_profile_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
    ]
