# Generated by Django 4.2.6 on 2023-12-23 17:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0002_alter_products_category_alter_products_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="slug",
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
