# Generated by Django 4.2.6 on 2023-12-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_products_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
