# Generated by Django 4.2.6 on 2023-12-27 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_bag_bagitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bagitem",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="products.products",
            ),
        ),
    ]
